p = input('digite algo:')
print('o tipo primitivo de {} é {}'.format(p, type(p)))
print('o que vc digitou é um numero ? {}'.format(p.isnumeric()))
print('o que vc digitou contem apenas letras ? {}'.format(p.isalpha()))
print('o que vc digitou está em maiusculo ? {}'.format(p.isupper()))
print('o que vc digitou está em minusculo ? {}'.format(p.islower()))
print('o que vc digitou é um espaço em branco ? {}'.format(p.isspace()))
print('o que vc digitou tem letra ou numero ? {}'.format(p.isalnum()))
print('o que vc digitou está capitalizado ? {}'.format(p.istitle()))
