print(20*'=')
print('DESFAZENDO NUMEROS 2')
print(20*'=')
numero = int(input('digite um numero entre 0 e 9999: '))
numero1 = str(numero)
print('unidade = {}'.format(numero1.strip()[3]))
print('dezena = {}'.format(numero1.strip()[2]))
print('centena = {}'.format(numero1.strip()[1]))
print('milhar {}'.format(numero1.strip()[0]))
